services:
  db:
    image: postgres:15
    container_name: sigc_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sigc
    ports:
      - "5435:5432"
    volumes:
      - sigc_data:/var/lib/postgresql/data

volumes:
  sigc_data:
